### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by firatbadur** [doublelam/react-native-free-canvas#1]
First of all, thank you for this package. I don't understand how I can add a picture to the background. I couldn't add a background image in any way. Can you help me?

`<FreeCanvas
            strokeColor={theme.colors.primary}
            strokeWidth={4}
            style={{flex: 1}}
            background={<Image source={{uri:uri}} style={{flex:1,height:300}}/>}
        />`

**Comment by doublelam** [comment]
Hi, try this image component https://shopify.github.io/react-native-skia/docs/images because the background component should be Skia component, they are children under <Canvas /> from Skia

**Comment by firatbadur** [comment]
Thanks it worked!
