### ISSUE TITLE
Add Skia path effect

### ISSUE THREAD

**Issue by muhamad-rizki** [doublelam/react-native-free-canvas#2]
Hello, thanks for this great library. Just one problem the line drawn is not smooth as expected
![image](https://github.com/user-attachments/assets/bd823607-cf5a-47af-9154-29370a06f786)

reading from the Skia docs it looks like possible to make the line drawn smoother with `CornerPathEffect` (https://shopify.github.io/react-native-skia/docs/path-effects#corner-path-effect), I tweaked your library and now the line are looks smoother
![image](https://github.com/user-attachments/assets/3d2d876f-62fb-4d7a-9f12-1eaa1c97cfea)

I added an optional props `pathEffect` on the component and passed it to the children of `Path` component, what do you think? I'll open PR if you like it

**Comment by doublelam** [comment]
That's cool, I was looking for a way to make the path look smooth, but I did not find any solution, if your solution works, please make a pr and I will merge it

Thanks

**Comment by muhamad-rizki** [comment]
Sure, I have opened a PR here #3
